export const routes = {
  home: '/',
  work: '/work',
  about: '/about',
  resume: '/resume',
  projects: '/projects',
  blog: 'https://blog.alexdevero.com/',
  blogLocal: '/blog',
  devero: 'https://devero.io/',
  login: '/login',
  contact: '/contact',
  notFound: '/404',
  caseStudyCdn77: '/case-study/cdn77',
  caseStudyDigitoo: '/case-study/digitoo',
  caseStudyPersoo: '/case-study/persoo',
  caseStudyRetino: '/case-study/retino',
  caseStudyStartMonday: '/case-study/start-monday',
  caseStudySupernova: '/case-study/supernova',
} as const
